title: 조재성 원장
logoImg: http://hani.chojaeseong.com/images/logo.png

theme:
  primary: "#FC5230"
  secondary: "#1ECECB"

authors:
  조재성:
    name: 조재성 원장
    comment: 재활, 통계, 프로그래밍을 전공한 수석졸업 한의사입니다.
    email: tingstyle1@gmail.com
    kakaotalk: tingstyle@hanmail.net
    profileImg: https://front.chojaeseong.com/images/png/profile/sub/02.png
  김석영:
    name: 김석영 원장
    comment: 20년이상 저와 가족, 지인들에게 한약을 통한 치료를 제공해온 한의사입니다.
    email: daisykim88@gmail.com
    kakaotalk: tingstyle@hanmail.net
#    profileImg: https://front.chojaeseong.com/images/png/profile/sub/01.png # 없으면 default_doctor_profile.png


ads:
  isAutoPlay: false
  autoPlayDuration: 1500
  pauseTimeoutDuration: 3000
  slides:
    광고1:
      type: video
      isMute: false
      youtubeId: pbGSI140UPw
      title: 첫번째 영상111111111
      subtitle: 원내광고 중입니다. 소리 음소거 안한 영상입니다.
    광고2:
      type: video
      isMute: false
      youtubeId: EMycmLvx9Hc
      title: 두번째 영상12222222222222222
      subtitle: 원내광고 중입니다. 소리 음소거 중인 영상입니다.
    광고3:
      type: image
      url: https://picstargram.s3.ap-northeast-2.amazonaws.com/post/93a4051d-089c-4bbe-bbea-8e2dc8298190_4700.webp
      title: 첫번째 그림
      subtitle: ㅋㅋㅋㅋ
    광고4:
      type: image
      url: https://picstargram.s3.ap-northeast-2.amazonaws.com/post/9a6ebc3f-ff00-46d9-b395-248cf7fc1642_4700.webp
      title: 2번째 그림
      subtitle: ㅋㅋㅋㅋ




footer:
  copyright:
    enabled: true
    company: (주) 김석영 주식회사
  give_credit: true

blog:
  titleLogoImg: https://front.chojaeseong.com/images/png/profile/sub/02.png # 없으면, default_title_logo.png

pagination: 5